# Generated by Django 4.2.5 on 2023-10-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gen_ai", "0003_remove_params_inst_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="params",
            name="inst_type",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
