# Generated by Django 4.2.5 on 2023-10-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gen_ai", "0004_params_inst_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="summ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=30)),
                ("model_name", models.CharField(max_length=30, null=True)),
                ("inst_type", models.CharField(max_length=30, null=True)),
                ("inst", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
